### ISSUE TITLE
Add a component path to every component data

### ISSUE THREAD

**Issue by pmi** [enonic/nextjs-enonic-demo#325]

**Comment by poi33** [comment]
@pmi done, close?

**Comment by pmi** [comment]
It says that it's archived in NextJS project already 📚

**Comment by pmi** [comment]
@alansemenov Is that correct that it is not closed after PR is merged ?

**Comment by poi33** [comment]
I was wondering about this too. We probably don't want auto close as this is done after every sprint

**Comment by alansemenov** [comment]
> @alansemenov Is that correct that it is not closed after PR is merged ?

Unfortunately, it's not (yet) automatic in Github projects :(. The one who merges a PR, should change status (or drag the issue) to "Done". You can close the issue as well, it will still remain in "Done". After sprint review we'll archive everything in "Done", so that these issues disappear from the dashboard.

**Comment by alansemenov** [comment]
Correction: the workflow was not entirely correct in the project. I've now changed it so that whenever an issue is closed (with the "Close" button), it will be automatically moved to "Done". So, whoever merges a PR, should close the issue. It will be moved to "Done", then manually archived after sprint review.
